name: 'User-mention'
description: 'Mention User On Slack'
inputs:
  who-to-mention-array:  # id of input
    description: 'Just Pass Array Of Objects Here'
    required: true
outputs:
  slackid: 
    description: 'returns user slack id'
  actor: 
    description: 'returns user github username'
  footer:
    description: 'footer of action'
runs:
  using: 'node16'
  main: 'dist/index.js'